version: '3.8'

services:
  # The Backend API Service (no changes here)
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file: # <--- ADD THIS SECTION
      - ./.env
    environment:
      - REDIS_HOST=redis
      - MLFLOW_TRACKING_URI=http://mlflow:5000 
    depends_on:
      - redis

  # The Redis Caching Service (no changes here)
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # --- NEW: The Frontend UI Service ---
  frontend:
    build: ./frontend  # Tells Docker to build from the ./frontend directory
    ports:
      - "8501:8501"    # Maps port 8501 on your server to port 8501 in the container
    depends_on:
      - backend        # Ensures the backend is running before the frontend starts

  mlflow:
    image: python:3.9-slim
    command: >
      sh -c "pip install mlflow &&
             mlflow server --host 0.0.0.0 --default-artifact-root /mlflow-artifacts"
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow-artifacts

  # NEW: Prometheus Monitoring Service
  prometheus:
    image: prom/prometheus
    ports:
      - "1000:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Mount the config file
    

  # NEW: Grafana Visualization Service
  grafana:
    image: grafana/grafana
    ports:
      - "1001:3000"
    depends_on:
      - prometheus
volumes:
  redis_data:
  mlflow_data: